### ISSUE TITLE
Fatals on v1.1.0

### ISSUE THREAD

**Issue by cagrimmett** [a8cteam51/internet-archive-wayback-machine-link-fixer#48] opened 2024-05-06 19:04 UTC
I loaded up the plugin on a test site of mine (https://cag-new-theme.mystagingwebsite.com) and ran into a blocker: Most of the link checks failed with this fatal:

~~~
PHP Fatal error: Uncaught TypeError: WPCOMSpecialProjects\Wayback_Link_Fixer\Link\Link_Repository::get_links_for_post(): 
Argument #1 ($post_id) must be of type int, bool given, called in /srv/htdocs/wp-content/plugins/wayback-link-fixer/src/WP_Post/WP_Post_Controller.php on line 154 and defined in /srv/htdocs/wp-content/plugins/wayback-link-fixer/src/Link/Link_Repository.php:294 
Stack trace: #0 /srv/htdocs/wp-content/plugins/wayback-link-fixer/src/WP_Post/WP_Post_Controller.php(154): WPCOMSpecialProjects\Wayback_Link_Fixer\Link\Link_Repository->get_links_for_post(false) 
#1 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(324): WPCOMSpecialProjects\Wayback_Link_Fixer\WP_Post\WP_Post_Controller->enqueue_frontend_script('') 
#2 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) 
#3 /wordpress/core/6.5.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#4 /wordpress/core/6.5.2/wp-includes/script-loader.php(2265): do_action('wp_enqueue_scri...') 
#5 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('') 
#6 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) 
#7 /wordpress/core/6.5.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#8 /wordpress/core/6.5.2/wp-includes/general-template.php(3050): do_action('wp_head') 
#9 /wordpress/core/6.5.2/wp-includes/template-canvas.php(17): wp_head() 
#10 /wordpress/core/6.5.2/wp-includes/template-loader.php(106): include('/wordpress/core...') 
#11 /wordpress/core/6.5.2/wp-blog-header.php(19): require_once('/wordpress/core...') 
#12 /wordpress/core/6.5.2/index.php(17): require('/wordpress/core...') 
#13 {main} thrown in /srv/htdocs/wp-content/plugins/wayback-link-fixer/src/Link/Link_Repository.php on line 294
~~~

Action scheduler has 1315 failed actions with the reason:
`action failed via WP Cron: Class "WPCOMSpecialProjects\Wayback_Link_Fixer\Processor\Post_Handler" not found`

**Comment by cagrimmett** [comment] 2024-05-06 19:07
I tested with creating new posts with some known broken links and working links, and edited some existing posts. I also let it be over the weekend to see if/when it would start processing existing posts.

**Comment by gin0115** [comment] 2024-05-07 09:39
Have patched the issue, it was an oversight which we might need to address.

The way this is works is we get all the links of the current post and localize them. We can then use JS to parse them and check links etc, the issue arises if we are loading an archive. Obviously, there are multiple posts, so multiple links and the global `$post` are not available when the scripts are enqueued.

So do we need this to work with things like infinite scroll and on archives, or just single posts? This is the draw back to doing it this was, rather than editing the links within the post content.

I might be able to change how this works, so rather than localizing the links as part of the enqueue process, instead we add a custom `<script>var links_for_{$post_id} = []</script>` to the start of the content (so even if using excerpts, it still rendered) or we could do an ajax/rest call to get the links for the post, but this might mean we get into a mess if someone has infinite scroll and a user just scrolls through 100's of posts on mobile in a few strong swipes.

**Comment by gin0115** [comment] 2024-05-07 09:39
[wayback-link-fixer.zip](https://github.com/a8cteam51/wayback-link-fixer/files/15233603/wayback-link-fixer.zip)
V 1.1.1

**Comment by gin0115** [comment] 2024-05-07 09:41
if you want to have a quick chat, let me know

**Comment by cagrimmett** [comment] 2024-05-09 21:00
The for the update, @gin0115. Unfortunately even on 1.1.1 all of my scheduled actions are still failing with:
`action failed via Async Request: Class "WPCOMSpecialProjects\Wayback_Link_Fixer\Processor\Post_Handler" not found`

Happy to do some investigation live on a call if it would help.

**Comment by gin0115** [comment] 2024-05-10 11:36
Hey

I did a few changes to class names and there are a few places where the search/replace missed. This has now been fixed and tested on multiple sites, both new and existing links are scanned.

I have found another little bug (well sort of) which makes debugging the scan existing posts a bit tricky (see issue #53) if you want to test how it handles existing posts that have been scanned before. You will need to clear some post meta keys (i will add this later to happen on uninstall when we drop the tables)

in phpmyadmin or similar, run this query ``SELECT * FROM `wp_postmeta` where meta_key = 't51_wlf_links';`` and delete the meta items. Now when the scan existing posts is run, it will not skip over those posts (we use that meta key existing as the "HAS BEEN CHECKED"). Obviously in normal use this wont be an issue, but should still be cleared if you choose to delete all links on uninstall to force recheck!)

**Comment by gin0115** [comment] 2024-05-10 11:37
Here is v1.1.2
[wayback-link-fixer.zip](https://github.com/a8cteam51/wayback-link-fixer/files/15274509/wayback-link-fixer.zip)

**Comment by gin0115** [comment] 2024-05-10 11:39
Probably not going to be a link you would use for testing, but for some reason TheGuardian (UK Newspaper) snapshots cant be found using the wayback api (but you can on the website). This stumped me for longer than i care to admit

> Can you guess what news site i often have open and grab lots of links from for testing...... 🤦🏼

**Comment by cagrimmett** [comment] 2024-05-16 21:21
@gin0115 I got further in my testing with this version. The post handler is no longer fataling and some links have been checked and more links keep getting added from existing posts, but a huge amount of links are not getting checked, and the Action Scheduler reports this as the reason:
> action failed via WP Cron: Reached maximum number of attempts for link with ID _[ID number]_

Happy to do some investigation live on a call on Monday if it would help.

**Comment by gin0115** [comment] 2024-05-17 13:43
Hmm

that would imply that it was not able to get an archived url from wayback. I had this with Guardian links, they could be found using the wayback website, but the api returned no snapshot found.

Can you let me know some of the urls?

Another thing to check is the logs for the `wpcomsp_wayback_link_fixer_archive_link` hook.

The way it works is 
`wpcomsp_wayback_link_fixer_archive_link` is fired, if the link already exists on the site, we grab the link id, if not we create a snapshot on wayback.

![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/714e2138-c5dd-435f-9127-2bc5b883a8fd)

If it says completed, that means it managed to create a snapshot**

Then 15 minuets after this (there is delay in them showing) we attempt to get the archive url, this will retry 5 times (15mins between attempts), if it still fails after 5 times then it just gives up.

To check the api, access this `https://archive.org/wayback/available/?url={URL}`

Example
https://archive.org/wayback/available/?url=https://redom.js.org/

**Comment by gin0115** [comment] 2024-05-17 13:46
** When i say it created a snapshot, the way this works is the page url loaded and then its created after some time has passed. 

Thorugh your contacts, do you mind finding out if there is a better way to create a snapshot?

im currently doing `https://web.archive.org/save/{URL}`

**Comment by cagrimmett** [comment] 2024-05-22 02:11
@gin0115 Thanks for the update!

Instead of this back and forth and an environment you can't access, I decided to set up a new testing environment with three different posts:
1. A post with 50 links I know are broken and have Archive.org snapshots
2. A post with 50 links I know are broken and probably do not have Archive.org snapshots, at least they didn't when I checked last year.
3. A post with ~175 links I'm fairly certain work and some of which have snapshots

I invited you as a collaborator: https://linkfixertesting-development.mystagingwebsite.com/

As of right now, all snapshots have been requested, but no link statuses have been checked. Hopefully those will populate overnight. 

Once the small case of posts is working as expected, I'd like to import content from a long-running site like Casnocha.com and let it run on those posts to see how it does. Export here: https://drive.google.com/drive/folders/1FjOqwJCdYFe4epaujQdgqywBYm4E2DFG?usp=sharing

**Comment by gin0115** [comment] 2024-05-22 08:32
Hey

Looking at the links, it looks like many have been populated as expected with archived links, i will list the ones not listed and investigate some of them

(10 results per page)

1. All ok
2. All ok
3. All ok
4. 1 missing
5. All ok
6. All ok
7. All ok
8. All ok
9. All ok
10. All ok
11. All ok
12. All ok
13. All ok
14. All ok
15. All ok
16. All ok
17. All ok
18. 1 missing
19. All ok
20. All ok
21. Al ok
22. All ok
23. All ok
24. All ok
25. All ok
26. All ok
27. All ok
28. All ok

Missing archives
* https://www.robinsloan.com/newsletters
* http://blog.youontop.com/gilad-gafni/redirect-non-www-to-www-in-wordpress-29.html

So of the 273 links only 2 could not find archives

**Comment by gin0115** [comment] 2024-05-22 08:34
https://www.robinsloan.com/newsletters

There are no snapshots when calling the api
`{"url": "https://www.robinsloan.com/newsletters", "archived_snapshots": {}}`
It is flagged as excluded 
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/b97e8365-fdd4-4784-8efb-c2bdf3bc3520)

**Comment by gin0115** [comment] 2024-05-22 08:37
http://blog.youontop.com/gilad-gafni/redirect-non-www-to-www-in-wordpress-29.html

There is no snapshot according to the api
`{"url": "http://blog.youontop.com/gilad-gafni/redirect-non-www-to-www-in-wordpress-29.html", "archived_snapshots": {}}`
BUT there are old snapshots when accessing the web ui
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/e3d46b19-534e-4c85-8988-dcaae38042ef)

BUt it implies 
* It returned a 4** on Nov 7th 2011
* It returned a 4** on Oct 12th 2007
* It returned a 3** on Dec 12th 2007

**Comment by gin0115** [comment] 2024-05-22 08:38
The status of the links will not be checked until we access as post with those links on the page and those links in the view port. 

I will do a backup now, so we have one before i check the posts, i will then monitor how it handles posts of 50 links (once with a slow scroll another with a quick flick down the screen and leave)

**Comment by gin0115** [comment] 2024-05-22 09:01
Tested `https://linkfixertesting-development.mystagingwebsite.com/sample-page/`
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/99214df7-cff6-4a68-a7a8-ffc0a5276399)
1 link, it found a 404 (gets a bit weird with `/wp-admin` links ive noticed, guessing they handle them in strange way As you can see from this wayback machine gave it as redirect with the final url as `/wp-admin/`
Shows in wp-admin
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/59b944a9-c155-45fb-a531-734131d8cb6d)
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/c06a7d50-5b3c-4d17-8558-cbfafac6cba2)

> I know the heading for the table is not great, `Link Health` would be better i think

**Comment by gin0115** [comment] 2024-05-22 09:27
Trying 'https://linkfixertesting-development.mystagingwebsite.com/2024/05/21/blogroll-links-should-work/' as a slow scroll

23 links checked almost instantly, most around 1sec, the slowest was 2.6s
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/bc3be397-071d-44a0-b3b5-4c3fa635ac17)

![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/f1a90bc4-0b00-442b-9a2e-e04ea64ab1c8)
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/a450bece-f580-4f9f-8bcb-77325c799de4)

Slowly scrolled the full viewport and 2 links were slow (14s and 6s) but again most are max 1 seconds and all done async
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/624cde6f-b85e-4c5c-8906-d1036e29222e)
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/555ebc99-7996-42aa-8721-064f29343041)
Next slow scroll 34 more links, slowest was 3.6s but most 1s again
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/f849ac4f-adf5-4288-a0bf-23bd9a3f56d6)
Again another slow scoll and hit 500 errors from server....Those that did not fail, all around 1s again
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/013f065f-4c3e-42a1-a968-629428059df1)

The errors
`"Service is offline"` - This happens when we dont get a 200 response back from the link checker api. All 7 have the same response. These should then be scanned again next time some access the page (will test/prove this after)

## FORGOT TO OPEN NETWORK TAB, MISSED THE NEXT BATCH 🤦🏼 
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/71e41d28-ea4d-4870-8603-d799985494a8)
Next batch again around 1s

> NOT TO SELF `HANDLE 500 ERRORS BETTER IN JS!`
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/defbf012-8301-417a-ba99-7bfb68702215)

**Comment by gin0115** [comment] 2024-05-22 09:29
Going to reload the page and check those links are checked again
They were all checked again and returned as expected
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/c8f2b622-94a4-48f1-a74d-042e59267e91)

**Comment by gin0115** [comment] 2024-05-22 09:38
`https://linkfixertesting-development.mystagingwebsite.com/2024/05/21/known-broken-no-replacements/`
I quickly scanned this post and of the 48 requests we had 
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/d35d07a8-918a-468b-b79f-3e2bfdf1f7ed)

1 x 404
5 x 500

## 404
This was caused by the link not being found, so its been missed when scanning the content
`http://www.flowdrops.com/2008/09/24/automattic-acquired-intensedebate%e2%80%99s-enhanced-comment-system/` - Will try to edit/save post and see if this gets found....
## 500 
As before service offline, guessing we are hitting some rate limits here!

Scanning times are slower, but im not sure if thats due to how fast i scrolled or not 🤷🏼

**Comment by gin0115** [comment] 2024-05-22 09:39
Quick scroll saw the missing 5 checked
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/a5ba671d-320d-4570-9871-f10d53c99382)

**Comment by gin0115** [comment] 2024-05-22 09:44
As for the broken link, saving doesnt retrigger it and i suspect its due to `%e2%80%99` being in the url, not sure if it fails the `is valild link` check we do to avoid adding links like `<a href="/#/page1">..</a>` or other situations where invalid links are used

Will investigate

**Comment by gin0115** [comment] 2024-05-22 09:46
Ive not checked the other post yet, but i would say looking at this, its working as expected and doesnt really have any noticeable performance issues

**Comment by gin0115** [comment] 2024-05-22 09:47
Do you want me to do a clone of that site locally or do we want to run it on this site?

**Comment by gin0115** [comment] 2024-05-22 10:13
Another thing to note, we only had 3 failed checks when looking for archived links
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/8e0a0011-cee8-4146-9466-949761f21e01)
# 234
This is the one above where it doesnt allow archived links
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/20fb51e1-9dac-47a9-8d2a-5390b3ae6874)

# 70
I havnt seen this one, it might have been on the list of links and i missed it being unable to get archived
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/be098f54-e006-4f73-83df-dccb5acbd9dd)
This answers that
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/903518c0-be00-4dc7-b909-d585273f1b51)

# 94
Again we know about this one from above
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/3836c390-3b13-4d31-989d-d91ded0c1557)

**Comment by cagrimmett** [comment] 2024-05-24 20:31
I imported ~3K posts from casnocha to see how those do. I'll try to click on some over the weekend. I'm out on Monday for the US holiday.

**Comment by gin0115** [comment] 2024-05-27 09:37
Had a quick look and it seems we now have 6421 links BUT we have 1079 Scheduled Actions fails

Did a quick scan of them
Lots at the start are amazon shortened links
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/f695d375-0a32-4d84-aa66-77853f7e163a)

I also found this one `Link URL - https://www.bloomberg.com/news/articles/2023-11-01/bill-gates-michael-dell-back-250-million-village-global-fund?srnd=undefined` now this does have a snapshot when i use the webui
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/ce545623-92e4-4110-b6bd-769079126015)

BUT when I use the same URL on the API i get no results
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/c8ea7842-c11a-4d1c-ae7f-19164a0dc8ee)

BUT if I drop the `?srnd=undefined` at the end I do get a result
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/4c401b04-5f84-46ad-8d81-2bf7d3f1e780)

So this means we need to decide how to deal with this, because obviously a site could have `http://www.url.com?p=14` as a valid url which is not the same as `http://www.url.com`. Obviously under the hood, way back know to drop the `?srnd=undefined` for the web ui. Could you ask them if we have access to this?

**Comment by gin0115** [comment] 2024-05-27 09:41
This is another one
https://linkfixertesting-development.mystagingwebsite.com/wp-admin/tools.php?page=wayback-link-fixer-links&wlf_link_id=6373


Link- `https://www.amazon.com/Lost-Found-Memoir-Kathryn-Schulz-ebook/dp/B09285Y1V4?crid=3V4Y43S280RX0&keywords=lost+and+found&qid=1673243510&sprefix=lost+and+fou%2Caps%2C149&sr=8-1&linkCode=ll1&tag=complainandresol&linkId=8be4679df853fa2dd5d6580f03726ce6&language=en_US&ref_=as_li_ss_tl`
WebUI has a snapshot, but checking the api gives 
```json
{"url": "https://www.amazon.com/Lost-Found-Memoir-Kathryn-Schulz-ebook/dp/B09285Y1V4?crid=3V4Y43S280RX0", "archived_snapshots": {}, "tag": "complainandresol"}
```
This has changed the url for me in the response, but added the tab
but if I check just `https://www.amazon.com/Lost-Found-Memoir-Kathryn-Schulz-ebook/dp/B09285Y1V4?crid=3V4Y43S280RX0` then I get no snapshots and the tag is not present

```json
{"url": "https://www.amazon.com/Lost-Found-Memoir-Kathryn-Schulz-ebook/dp/B09285Y1V4?crid=3V4Y43S280RX0", "archived_snapshots": {}}
```

**Comment by gin0115** [comment] 2024-05-27 10:11
Until page 9 the only links which could not find an archive are the 2 above and various amazon links, but on page 9 i hit one for apple podcasts

Link Details - https://podcasts.apple.com/us/podcast/ben-casnocha-on-his-learnings-from-working-reid-hoffman/id1535501313?i=1000529477521
URL - https://podcasts.apple.com/us/podcast/ben-casnocha-on-his-learnings-from-working-reid-hoffman/id1535501313?i=1000529477521

This link has not been archived, it looks like were not able to create the archive for this
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/68b6cb48-a33d-4d77-8014-2a15b2758e01)

I was able to manually create a snapshot for this, so im guessing there was an error when we attempted initially!

I am also able to access the snapshot via the api afterwards too

**Comment by gin0115** [comment] 2024-05-27 10:14
Still moving ahead we have lots of amazon links
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/db443962-a806-449a-8fbe-617808d8a15c)
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/b8ae80dd-f122-4734-9f66-89e1399034b6)

**Comment by gin0115** [comment] 2024-05-27 10:16
Another example of links found in webui, but not api

https://casnocha.com/?s=meghan+daum

![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/11882a5f-5cb4-486c-b164-597232cc083a)
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/e4ea50f8-ff53-461f-83e6-d6333acd1b86)

The archives on this are a bit odd to as the jetpack instant search opens and then fails

**Comment by gin0115** [comment] 2024-05-27 10:19
Some are legit fails
URL https://www.target.com/p/men-s-10-cats-board-shorts-s/-/A-54024488?ref=tgt_adv_XS000000&AFID=google_pla_df&fndsrc=tgtao&CPNG=PLA_Men%2BShopping_Local&adgroup=SC_Men_Local&LID=700000001170770pgs&network=g&device=c&location=9032065&ds_rl=1246978&ds_rl=1246978&ds_rl=1241788&gclid=CjwKCAjwtajrBRBVEiwA8w2Q8PrPiDhRB20QAmqoN03zwyWpxJwAjw5NoMo0JTp3pXWaWioecsVYBxoCJ2wQAvD_BwE&gclsrc=aw.ds
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/5bdf0b28-5a33-49e5-a58e-b43a89267e2e)

**Comment by gin0115** [comment] 2024-05-27 10:25
Found another example of a link failing to be archived. 
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/dce9acb6-c214-4ae2-833a-74f1d0cc89c5)
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/27965ab1-2f14-4297-9704-28a4a119f798)

This is a hard one to deal with!

The way it works is we attempt to create a snapshot, BUT due to how long it can take to give a response, i dont wait on the reply, but it seems trying to do thousands at once causes an issue here.

Will have a think, but might be worth us hopping on a call and we can go through it. 

(going to check a few more, but there is a general trend)

**Comment by gin0115** [comment] 2024-05-27 10:27
Numerous internal links not being archived, i thought i had left in the logic to not check lcoal links, but looks like it didnt make the numerous rewrites.

**Comment by gin0115** [comment] 2024-05-27 10:28
Some http://bit.ly/LFL-Article links not archived

**Comment by gin0115** [comment] 2024-06-04 15:58
Following up on the issue above with `http://www.flowdrops.com/2008/09/24/automattic-acquired-intensedebate%e2%80%99s-enhanced-comment-system`

Its now being indexed and working as expected, so not sure what the issue was then
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/2492cc6d-9562-4f5f-8f91-f3f87264a7da)

**Comment by gin0115** [comment] 2024-06-04 16:17
Update

I have give @cagrimmett the latest version of the plugin, it contains a large number of fixes, improvements and new flows

## Fixes
* Link validity is now handled better, broken links can be marked as fixed now and wont set broken on the initial call, until the count of consecutive failures has been passed
* Links without Archived links will not have the `href` updated in the front end
* Invalid HTML will no long throw an error when content is scanned 

## Improvements
* UI for single reports has been done, this is inline with regular metaboxes, even if its an admin page
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/5ec621ed-9d5f-4fa6-94a4-840a3ff77e8c)
* Filters, search and links per page has been added to the link list page
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/921b5762-06e9-4ad9-a1f8-04c791afc216)
* Event class names and hooks have been updated to reflect the purpose better
* Checking links, Updating the links archived URL and creating (then updating archive) new snapshot for links allowed from table

## Flow
The flow has changed, now we grab the job id from wayback machine when we create a snapshot. If we failed to get a job id, we add to the queue with a delay and attempt 5 times.
Once we have a job id, we keep checking the status and allow this for 5 times
Once we know the status, we either mark the link with no archive link (and log the error message from snapshot progress) or if successful we then attempt to update the links archive link from the latest snapshot.

All of these have multiple processes and the reattempts are added with a dealy to try and avoid and rate limiting.

**Comment by gin0115** [comment] 2024-06-04 16:18
Still outstanding.

Labels on bulk actions are not great, nor are the filters
Link meta is not removed when we uninstall
Still have the weird issue with some url params

**Comment by gin0115** [comment] 2024-06-05 14:40
Have left this running on a large site locally and it was running fine for a while and then we started getting lots of failures.

I added some logging and started to see 
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/30081ec3-3e7f-48cc-93af-61fbd0e0186e)

So i dug a little deeper and saw the create-snapshot actions was failing after the alloted retries 
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/f10efaeb-865c-4620-9adb-6d8f0c678515)

I added more logging to dig deeper (the issue was unable to get job id) and found this in the responses
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/0ce855c5-3c21-4946-b4bc-99915374cb27)
We did have some earlier issues too where we got 5** responses back
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/712a10a7-69d4-42de-b0ce-1fb51296bbff)

**Comment by gin0115** [comment] 2024-06-05 14:45
Im not sure whats the best approach here, the current flow sees a new snapshot created every time we see a new link. For new posts, this is what we want as it will be a snapshot at the time we created the link, so its what is being linked to should it be cleared.

However if (like the above example) we have over 8900 links (and it is still not finished processing all the existing posts), that's a LOT of links being possibly created 

My current thinking is to set a flag when doing old posts to do a `find or create` and then with new posts, we do a `create`.

**Comment by gin0115** [comment] 2024-06-07 22:12
Have left the local version of tim.blog running to do all the links, we had some issues along the way, so some of the links are possibly badly encoded this might account for a few thousand, but i cant say for sure and without clearing all the links on posts, running it again, i wont know for sure. 

We also hadnt patched out all the timeouts and limits of 200 snapshots per day, but

We have 48k links in total
10,600 do not have archived links, for a raft of reasons.

(please note even fails with retries get logged, so this is not the full picture, but gives a rough idea)
13,153 failed events 

Breakdown by action
``` txt
wlf_update_archive_url = 2975
wlf_create_new_snapshot = 6508
wlf_check_snapshot_status = 3668
wlf_find_or_create_snapshot = 2
 ```
5449 links are to Amazon and many of these fail
1000 were caused by Curl issues, so when archive was not responding
163 of the links now return a 404
1300 exceeded the retries limit for updating the archived url. This is either due to fails when creating them or being blocked like the guardian
2100 exceeded the retries limit for creating snapshots, either exceded 200 limit, blocked urls or 404
243 exceeded the check snapshot limit, this is slightly concerning as we wait 1 min between each check and at this volume, the rechecks could be 2hrs apart, but out of almost 50k links, this is a 0.4% fatal error rate
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/7bba8cb1-a5dd-4819-9ca4-556b640b5775)

**Comment by gin0115** [comment] 2024-06-07 22:15
I will clean up the code a little bit more and update all the docs, we can then put it up on some other sites for testing. Might be worth putting it up on a dev copy of something like TechDirt or possibly the staging version of tim.blog to give it a run without the initial 200 limit. Most of the snapshots will already be created, so it will be a much quicker process now we do `find or create` up front.

**Comment by gin0115** [comment] 2024-08-12 12:38
this has now been cleaned up and all the above issues are resolved. Closing this to clean up the issues

**Closed as completed by gin0115** 2024-08-12 12:38 UTC
